
rule identify_impurity:
    input:
        r1=lambda wildcards: SAMPLES[wildcards.sample]["R1"],
        r2=lambda wildcards: SAMPLES[wildcards.sample]["R2"],
    output:
        kraken_trigger_txt=OUT + "/identify_impurity/{sample}/{sample}.skipped-or-not.txt"
    message:
        "Running species identification for {wildcards.sample}."
    log:
        OUT + "/log/identify_impurity/{sample}.log",
    threads: config["threads"]["kraken2"]
    #conda:
    #    "../envs/identify_species.yaml"
    #container:
    #    "library://alesr13/default/kraken2_bracken:v2.1.2_v2.6.1"
    params:
        kraken_db_dir=config["kraken_db_dir"],
        # output files generated by kraken/bracken.
        # But tool is --optional, so can't define these in output: directive
        kraken2_kreport = OUT + "/identify_impurity/{sample}/{sample}.kreport2",
        bracken_s = OUT + "/identify_impurity/{sample}/{sample}_species_content.txt"
    resources:
        mem_gb=config["mem_gb"]["kraken2"],
    run:
        if not params.kraken_db_dir:
            # No Kraken database available; skip this rule completely
            # write the output.kraken_trigger_txt file -> SKIPPED
            shell("""
                echo "kraken impurity analyses of {wildcards.sample}: SKIPPED" > {output.kraken_trigger_txt};
            """)
        else:
            # Kraken database available!
            shell("""
        # Adding --confidence 0.05 causes 0 kmers assigned to species in some samples
        # That breaks bracken
        kraken2 --db {params.kraken_db} \
            --threads {threads} \
            --report {params.kraken2_kreport} \
            --gzip-compressed \
            --paired \
            --output - \
            {input.r1} {input.r2}  &> {log};
        bracken -d {params.kraken_db} \
            -i {params.kraken2_kreport} \
            -o {params.bracken_s} \
            -r 150 \
            -l S \
            -t 0  &>> {log}
        # write the output.kraken_trigger_txt file -> DONE
        echo "kraken impurity analyses of {wildcards.sample} [on {params.kraken_db_dir]}: DONE" > {output.kraken_trigger_txt};
        """)
