sample1:
  R1: /home/boas/analysis/juno/raw_reads/sample1_R1.fq.gz
  R2: /home/boas/analysis/juno/raw_reads/sample1_R2.fq.gz
sample2:
  R1: /home/boas/analysis/juno/raw_reads/sample2_R1.fq.gz
  R2: /home/boas/analysis/juno/raw_reads/sample2_R2.fq.gz
sample3:
  R1: /home/boas/analysis/juno/raw_reads/sample3_R1.fq.gz
  R2: /home/boas/analysis/juno/raw_reads/sample3_R2.fq.gz
